# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: job_orchestrator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'job_orchestrator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16job_orchestrator.proto\x12\x1c\x65xobrain.job_orchestrator.v1\"]\n\x16KnowledgeUpdateMessage\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x10\n\x08sequence\x18\x03 \x01(\x05\x12\x12\n\ncreated_at\x18\x04 \x01(\t\"\x99\x01\n\x16KnowledgeUpdatePayload\x12\x19\n\x11journal_reference\x18\x01 \x01(\t\x12\x46\n\x08messages\x18\x02 \x03(\x0b\x32\x34.exobrain.job_orchestrator.v1.KnowledgeUpdateMessage\x12\x1c\n\x14requested_by_user_id\x18\x03 \x01(\t\"\xab\x01\n\x11\x45nqueueJobRequest\x12\x10\n\x08job_type\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12P\n\x10knowledge_update\x18\x03 \x01(\x0b\x32\x34.exobrain.job_orchestrator.v1.KnowledgeUpdatePayloadH\x00\x12\x16\n\x0cpayload_json\x18\x04 \x01(\tH\x00\x42\t\n\x07payload\"!\n\x0f\x45nqueueJobReply\x12\x0e\n\x06job_id\x18\x01 \x01(\t2\x7f\n\x0fJobOrchestrator\x12l\n\nEnqueueJob\x12/.exobrain.job_orchestrator.v1.EnqueueJobRequest\x1a-.exobrain.job_orchestrator.v1.EnqueueJobReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'job_orchestrator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_KNOWLEDGEUPDATEMESSAGE']._serialized_start=56
  _globals['_KNOWLEDGEUPDATEMESSAGE']._serialized_end=149
  _globals['_KNOWLEDGEUPDATEPAYLOAD']._serialized_start=152
  _globals['_KNOWLEDGEUPDATEPAYLOAD']._serialized_end=305
  _globals['_ENQUEUEJOBREQUEST']._serialized_start=308
  _globals['_ENQUEUEJOBREQUEST']._serialized_end=479
  _globals['_ENQUEUEJOBREPLY']._serialized_start=481
  _globals['_ENQUEUEJOBREPLY']._serialized_end=514
  _globals['_JOBORCHESTRATOR']._serialized_start=516
  _globals['_JOBORCHESTRATOR']._serialized_end=643
# @@protoc_insertion_point(module_scope)
