# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import knowledge_pb2 as knowledge__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in knowledge_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KnowledgeInterfaceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/exobrain.knowledge.v1.KnowledgeInterface/Health',
                request_serializer=knowledge__pb2.HealthRequest.SerializeToString,
                response_deserializer=knowledge__pb2.HealthReply.FromString,
                _registered_method=True)
        self.GetSchema = channel.unary_unary(
                '/exobrain.knowledge.v1.KnowledgeInterface/GetSchema',
                request_serializer=knowledge__pb2.GetSchemaRequest.SerializeToString,
                response_deserializer=knowledge__pb2.GetSchemaReply.FromString,
                _registered_method=True)
        self.GetUpsertGraphDeltaJsonSchema = channel.unary_unary(
                '/exobrain.knowledge.v1.KnowledgeInterface/GetUpsertGraphDeltaJsonSchema',
                request_serializer=knowledge__pb2.GetUpsertGraphDeltaJsonSchemaRequest.SerializeToString,
                response_deserializer=knowledge__pb2.GetUpsertGraphDeltaJsonSchemaReply.FromString,
                _registered_method=True)
        self.GetExtractionSchemaContext = channel.unary_unary(
                '/exobrain.knowledge.v1.KnowledgeInterface/GetExtractionSchemaContext',
                request_serializer=knowledge__pb2.GetExtractionSchemaContextRequest.SerializeToString,
                response_deserializer=knowledge__pb2.GetExtractionSchemaContextReply.FromString,
                _registered_method=True)
        self.GetEntityTypePropertyContext = channel.unary_unary(
                '/exobrain.knowledge.v1.KnowledgeInterface/GetEntityTypePropertyContext',
                request_serializer=knowledge__pb2.GetEntityTypePropertyContextRequest.SerializeToString,
                response_deserializer=knowledge__pb2.GetEntityTypePropertyContextReply.FromString,
                _registered_method=True)
        self.UpsertSchemaType = channel.unary_unary(
                '/exobrain.knowledge.v1.KnowledgeInterface/UpsertSchemaType',
                request_serializer=knowledge__pb2.UpsertSchemaTypeRequest.SerializeToString,
                response_deserializer=knowledge__pb2.UpsertSchemaTypeReply.FromString,
                _registered_method=True)
        self.UpsertGraphDelta = channel.unary_unary(
                '/exobrain.knowledge.v1.KnowledgeInterface/UpsertGraphDelta',
                request_serializer=knowledge__pb2.UpsertGraphDeltaRequest.SerializeToString,
                response_deserializer=knowledge__pb2.UpsertGraphDeltaReply.FromString,
                _registered_method=True)
        self.GetUserInitGraph = channel.unary_unary(
                '/exobrain.knowledge.v1.KnowledgeInterface/GetUserInitGraph',
                request_serializer=knowledge__pb2.GetUserInitGraphRequest.SerializeToString,
                response_deserializer=knowledge__pb2.GetUserInitGraphReply.FromString,
                _registered_method=True)
        self.FindEntityCandidates = channel.unary_unary(
                '/exobrain.knowledge.v1.KnowledgeInterface/FindEntityCandidates',
                request_serializer=knowledge__pb2.FindEntityCandidatesRequest.SerializeToString,
                response_deserializer=knowledge__pb2.FindEntityCandidatesReply.FromString,
                _registered_method=True)
        self.ListEntitiesByType = channel.unary_unary(
                '/exobrain.knowledge.v1.KnowledgeInterface/ListEntitiesByType',
                request_serializer=knowledge__pb2.ListEntitiesByTypeRequest.SerializeToString,
                response_deserializer=knowledge__pb2.ListEntitiesByTypeReply.FromString,
                _registered_method=True)
        self.GetEntityContext = channel.unary_unary(
                '/exobrain.knowledge.v1.KnowledgeInterface/GetEntityContext',
                request_serializer=knowledge__pb2.GetEntityContextRequest.SerializeToString,
                response_deserializer=knowledge__pb2.GetEntityContextReply.FromString,
                _registered_method=True)


class KnowledgeInterfaceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSchema(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUpsertGraphDeltaJsonSchema(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExtractionSchemaContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEntityTypePropertyContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertSchemaType(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertGraphDelta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserInitGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindEntityCandidates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEntitiesByType(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEntityContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KnowledgeInterfaceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=knowledge__pb2.HealthRequest.FromString,
                    response_serializer=knowledge__pb2.HealthReply.SerializeToString,
            ),
            'GetSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSchema,
                    request_deserializer=knowledge__pb2.GetSchemaRequest.FromString,
                    response_serializer=knowledge__pb2.GetSchemaReply.SerializeToString,
            ),
            'GetUpsertGraphDeltaJsonSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUpsertGraphDeltaJsonSchema,
                    request_deserializer=knowledge__pb2.GetUpsertGraphDeltaJsonSchemaRequest.FromString,
                    response_serializer=knowledge__pb2.GetUpsertGraphDeltaJsonSchemaReply.SerializeToString,
            ),
            'GetExtractionSchemaContext': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExtractionSchemaContext,
                    request_deserializer=knowledge__pb2.GetExtractionSchemaContextRequest.FromString,
                    response_serializer=knowledge__pb2.GetExtractionSchemaContextReply.SerializeToString,
            ),
            'GetEntityTypePropertyContext': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEntityTypePropertyContext,
                    request_deserializer=knowledge__pb2.GetEntityTypePropertyContextRequest.FromString,
                    response_serializer=knowledge__pb2.GetEntityTypePropertyContextReply.SerializeToString,
            ),
            'UpsertSchemaType': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertSchemaType,
                    request_deserializer=knowledge__pb2.UpsertSchemaTypeRequest.FromString,
                    response_serializer=knowledge__pb2.UpsertSchemaTypeReply.SerializeToString,
            ),
            'UpsertGraphDelta': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertGraphDelta,
                    request_deserializer=knowledge__pb2.UpsertGraphDeltaRequest.FromString,
                    response_serializer=knowledge__pb2.UpsertGraphDeltaReply.SerializeToString,
            ),
            'GetUserInitGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserInitGraph,
                    request_deserializer=knowledge__pb2.GetUserInitGraphRequest.FromString,
                    response_serializer=knowledge__pb2.GetUserInitGraphReply.SerializeToString,
            ),
            'FindEntityCandidates': grpc.unary_unary_rpc_method_handler(
                    servicer.FindEntityCandidates,
                    request_deserializer=knowledge__pb2.FindEntityCandidatesRequest.FromString,
                    response_serializer=knowledge__pb2.FindEntityCandidatesReply.SerializeToString,
            ),
            'ListEntitiesByType': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEntitiesByType,
                    request_deserializer=knowledge__pb2.ListEntitiesByTypeRequest.FromString,
                    response_serializer=knowledge__pb2.ListEntitiesByTypeReply.SerializeToString,
            ),
            'GetEntityContext': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEntityContext,
                    request_deserializer=knowledge__pb2.GetEntityContextRequest.FromString,
                    response_serializer=knowledge__pb2.GetEntityContextReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'exobrain.knowledge.v1.KnowledgeInterface', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('exobrain.knowledge.v1.KnowledgeInterface', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KnowledgeInterface(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exobrain.knowledge.v1.KnowledgeInterface/Health',
            knowledge__pb2.HealthRequest.SerializeToString,
            knowledge__pb2.HealthReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exobrain.knowledge.v1.KnowledgeInterface/GetSchema',
            knowledge__pb2.GetSchemaRequest.SerializeToString,
            knowledge__pb2.GetSchemaReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUpsertGraphDeltaJsonSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exobrain.knowledge.v1.KnowledgeInterface/GetUpsertGraphDeltaJsonSchema',
            knowledge__pb2.GetUpsertGraphDeltaJsonSchemaRequest.SerializeToString,
            knowledge__pb2.GetUpsertGraphDeltaJsonSchemaReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetExtractionSchemaContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exobrain.knowledge.v1.KnowledgeInterface/GetExtractionSchemaContext',
            knowledge__pb2.GetExtractionSchemaContextRequest.SerializeToString,
            knowledge__pb2.GetExtractionSchemaContextReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEntityTypePropertyContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exobrain.knowledge.v1.KnowledgeInterface/GetEntityTypePropertyContext',
            knowledge__pb2.GetEntityTypePropertyContextRequest.SerializeToString,
            knowledge__pb2.GetEntityTypePropertyContextReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertSchemaType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exobrain.knowledge.v1.KnowledgeInterface/UpsertSchemaType',
            knowledge__pb2.UpsertSchemaTypeRequest.SerializeToString,
            knowledge__pb2.UpsertSchemaTypeReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertGraphDelta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exobrain.knowledge.v1.KnowledgeInterface/UpsertGraphDelta',
            knowledge__pb2.UpsertGraphDeltaRequest.SerializeToString,
            knowledge__pb2.UpsertGraphDeltaReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserInitGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exobrain.knowledge.v1.KnowledgeInterface/GetUserInitGraph',
            knowledge__pb2.GetUserInitGraphRequest.SerializeToString,
            knowledge__pb2.GetUserInitGraphReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindEntityCandidates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exobrain.knowledge.v1.KnowledgeInterface/FindEntityCandidates',
            knowledge__pb2.FindEntityCandidatesRequest.SerializeToString,
            knowledge__pb2.FindEntityCandidatesReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEntitiesByType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exobrain.knowledge.v1.KnowledgeInterface/ListEntitiesByType',
            knowledge__pb2.ListEntitiesByTypeRequest.SerializeToString,
            knowledge__pb2.ListEntitiesByTypeReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEntityContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exobrain.knowledge.v1.KnowledgeInterface/GetEntityContext',
            knowledge__pb2.GetEntityContextRequest.SerializeToString,
            knowledge__pb2.GetEntityContextReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
