INSERT INTO knowledge_graph_schema_types (id, kind, name, description, active)
VALUES
  ('node.universe', 'node', 'Universe', 'Top-level world scope', TRUE),
  ('node.entity', 'node', 'Entity', 'Base world-model node', TRUE),
  ('node.person', 'node', 'Person', 'Person entity subtype', TRUE),
  ('node.group', 'node', 'Group', 'Group/faction/family subtype', TRUE),
  ('node.institution', 'node', 'Institution', 'Institution subtype', TRUE),
  ('node.place', 'node', 'Place', 'Place/location subtype', TRUE),
  ('node.object', 'node', 'Object', 'Physical object/artifact subtype', TRUE),
  ('node.concept', 'node', 'Concept', 'Concept/topic/theme subtype', TRUE),
  ('node.species', 'node', 'Species', 'Species subtype', TRUE),
  ('node.event', 'node', 'Event', 'Time-bound event subtype', TRUE),
  ('node.task', 'node', 'Task', 'Event subtype with due date intent', TRUE),
  ('node.block', 'node', 'Block', 'Content-bearing block node', TRUE),
  ('node.quote', 'node', 'Quote', 'Block subtype for quotations', TRUE),
  ('node.image', 'node', 'Image', 'Block subtype for image annotations', TRUE),
  ('edge.is_part_of', 'edge', 'IS_PART_OF', 'Entity belongs to a universe', TRUE),
  ('edge.described_by', 'edge', 'DESCRIBED_BY', 'Entity page root block', TRUE),
  ('edge.summarizes', 'edge', 'SUMMARIZES', 'Summary block points to detail block', TRUE),
  ('edge.mentions', 'edge', 'MENTIONS', 'Block references entity', TRUE),
  ('edge.related_to', 'edge', 'RELATED_TO', 'Generic relation fallback', TRUE),
  ('edge.at', 'edge', 'AT', 'Entity/event/task located at place', TRUE),
  ('edge.lies_in', 'edge', 'LIES_IN', 'Place containment hierarchy', TRUE),
  ('edge.contains', 'edge', 'CONTAINS', 'Container holds item/entity', TRUE),
  ('edge.knows', 'edge', 'KNOWS', 'Person knows person', TRUE),
  ('edge.member_of', 'edge', 'MEMBER_OF', 'Person belongs to group', TRUE),
  ('edge.affiliated_with', 'edge', 'AFFILIATED_WITH', 'Person linked to institution', TRUE),
  ('edge.participated_in', 'edge', 'PARTICIPATED_IN', 'Person in event', TRUE),
  ('edge.involves', 'edge', 'INVOLVES', 'Event links to involved entity', TRUE),
  ('edge.before', 'edge', 'BEFORE', 'Event ordering relation', TRUE),
  ('edge.causes', 'edge', 'CAUSES', 'Event causality relation', TRUE),
  ('edge.assigned_to', 'edge', 'ASSIGNED_TO', 'Task assigned to person', TRUE),
  ('edge.done_for', 'edge', 'DONE_FOR', 'Task done for entity', TRUE),
  ('edge.depends_on', 'edge', 'DEPENDS_ON', 'Task dependency relation', TRUE),
  ('edge.about', 'edge', 'ABOUT', 'Entity is about concept', TRUE),
  ('edge.instance_of', 'edge', 'INSTANCE_OF', 'Entity instance classification', TRUE),
  ('edge.also_known_as', 'edge', 'ALSO_KNOWN_AS', 'Alias relation', TRUE),
  ('edge.same_as', 'edge', 'SAME_AS', 'Strong identity equivalence', TRUE),
  ('block.default', 'block', 'Block', 'Default block type', TRUE),
  ('block.quote', 'block', 'Quote', 'Quote block type', TRUE),
  ('block.image', 'block', 'Image', 'Image block type', TRUE)
ON CONFLICT (id) DO UPDATE
SET
  kind = EXCLUDED.kind,
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  active = EXCLUDED.active,
  updated_at = NOW();
