# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import job_orchestrator_pb2 as job__orchestrator__pb2

class JobOrchestratorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnqueueJob = channel.unary_unary(
                '/exobrain.job_orchestrator.v1.JobOrchestrator/EnqueueJob',
                request_serializer=job__orchestrator__pb2.EnqueueJobRequest.SerializeToString,
                response_deserializer=job__orchestrator__pb2.EnqueueJobReply.FromString,
                _registered_method=True)


class JobOrchestratorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EnqueueJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JobOrchestratorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnqueueJob': grpc.unary_unary_rpc_method_handler(
                    servicer.EnqueueJob,
                    request_deserializer=job__orchestrator__pb2.EnqueueJobRequest.FromString,
                    response_serializer=job__orchestrator__pb2.EnqueueJobReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'exobrain.job_orchestrator.v1.JobOrchestrator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('exobrain.job_orchestrator.v1.JobOrchestrator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class JobOrchestrator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EnqueueJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exobrain.job_orchestrator.v1.JobOrchestrator/EnqueueJob',
            job__orchestrator__pb2.EnqueueJobRequest.SerializeToString,
            job__orchestrator__pb2.EnqueueJobReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
